# Generated by Django 2.2 on 2021-04-27 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoFormsApp', '0002_dragon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragon',
            name='name',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='dragon',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dragons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
