# Generated by Django 3.1.7 on 2021-03-22 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theWallApplication', '0003_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='postIBelongTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='theWallApplication.post'),
            preserve_default=False,
        ),
    ]
